version: '3.7'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home-automation
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  app:
    depends_on:
      - mariadb
      - mosquitto
    links:
      - mariadb
      - mosquitto
    environment:
      MQTT_HOST: mosquitto
      DB_HOST: mariadb
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8090:8090"
    restart: always
volumes:
  data: