version: '3.3'
services:
  mariadb:
    image: tobi312/rpi-mariadb:10.6-alpine
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: home-automation
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 60s
      timeout: 5s
      retries: 5
    network_mode: bridge
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    network_mode: bridge
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto_pub -h localhost -t test -m 'test' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    depends_on:
      mariadb:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    links:
      - mariadb
      - mosquitto
    environment:
      MQTT_HOST: mosquitto
      DB_HOST: mariadb
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8090:8090"
    restart: always
    network_mode: bridge
volumes:
  data: